name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        npm install
        npm run build
        docker build . --file Dockerfile --tag my-image-name:build
        docker push my-image-name:build
